web:
  Port: 8081
  EnablePprof: false
  AppMode: "development"
  LogLevel: "info"
  LogSaveDay: 7
  LogSplitTime: 24
  LogOutType: "json"
  LogOutPath: "file"
  StartTime: 

redis:
  Host: "127.0.0.1"
  Port:
  Password:

mysql:
  Host: "127.0.0.1"
  Port: 3306
  User: "root"
  Password: "xxxxx.yaml"
  DB: "dbname"
  EnableDebug: false